neighbourhood/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('neighbours.urls')),
    path('', include('django.contrib.auth.urls')),
]

neighbours/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.home, name='home'),
    path('profile/',views.profile, name='profile'),
    path('business/',views.business, name='business'),
    path('nineOneone/',views.contact, name='nineOneone'),
    path('register/',views.register, name='register'),
    path('post',views.post,name='post'),
]

neighbours/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
# Create your models here.

LOCATION_CHOICES = (
    ('Nairobi','Nairobi'),
    ('Kisumu','Mombasa'),
    ('Mombasa','Mombasa'),
)

NEIGHBORHOOD_CHOICES = (
    ('Juja', 'Juja'),
    ('Kinoo','Kinoo'),
    ('Eastleigh','Eastleigh'),
    ('Zimmerman','Zimmerman'),
    ('Ruiru','Ruiru'),
    ('Donholm','Donholm'),
)

class Neighborhood(models.Model):
    name = models.CharField(max_length=50,choices=NEIGHBORHOOD_CHOICES)
    location = models.CharField(max_length=70,choices=LOCATION_CHOICES)
    
    def create_neighborhood(self):
        self.save()
        
    def delete_neighborhodd(self):
        self.delete()
        
    def find_neighborhood(self, id):
        return Neighborhood.objects.get(id=id)
    
    def update_neighborhood(self):
        self.save()
    
    
    def __str__(self):
        return f"{self.location}/{self.name}"
    
class Profile(models.Model):
    image = CloudinaryField('image', null=True)
    username = models.CharField(max_length=100)
    email = models.EmailField()
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.CASCADE, null=True)
    bio = models.TextField()
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username
    
class Business(models.Model):
    image = CloudinaryField('image', null=True)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    
    def create_business(self):
        self.save()
    
    def delete_business(self):
        self.delete()
    
    def find_businesss(self,id):
        return Business.objects.get(id=id)
    
    def update_business(self):
        self.save()
    
    def __str__(self):
        return self.name
    
class Contact(models.Model):
    name = models.CharField(max_length=50)
    number = models.CharField(max_length=100)
    neighborhood = models.ForeignKey(Neighborhood,on_delete=models.CASCADE,null=True)
    
    def __str__(self):
        return f"{self.name} {self.neighborhood.name}"

        
class Post(models.Model):
    title = models.CharField(max_length=100, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    content = models.TextField(blank=True, null=True)
    profile_photo = CloudinaryField("image",blank=True,null=True)
    created_on = models.DateTimeField(auto_now_add=True,null=True)
    updated_on = models.DateTimeField(auto_now=True,null=True)
    class Meta:
        ordering = ['-pk']
    def __str__(self):
        return f'{self.title} Post'
    def delete_post(self):
        self.delete()
    def create_post(self):
        self.save()
    def update_post(self):
        self.update()

# Create your models here.

neighbours/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Business
from.models import *

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        
class ProfileEdit(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image','username','email','neighborhood','bio']
        
class BusinessForm(forms.ModelForm):
    class Meta:
        model = Business
        fields = ['image','name','email','neighborhood']
        
class SearchForm(forms.Form):
    search = forms.CharField(max_length=100)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields=['title','content',]
        exclude = ['user']

neighbours/views.py
from django.shortcuts import render
from django.shortcuts import redirect, render
from .models import Business, Contact, Neighborhood, Profile
from .forms import RegisterForm, ProfileEdit, BusinessForm, SearchForm, PostForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required


# Create your views here.

@login_required(login_url='login')
def home(request):
    form = BusinessForm()
    searchform = SearchForm()
    if request.method=='POST':
        form = BusinessForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.cleaned_data['image']
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            neighborhood = form.cleaned_data['neighborhood']
            created = Business(image=image, name=name,email=email,neighborhood=neighborhood,user=request.user)
            created.save()
            return redirect('business')

    if request.method == 'POST':
        searchform = SearchForm(request.POST)
        if searchform.is_valid():
            name = searchform.cleaned_data['search']
            try:
                business = Business.objects.get(name=name)
                return redirect('business')
            except Exception:
                return redirect('home')


    return render(request, 'all neighbours/index.html',{"title":'Home','form':form,'searchform':searchform})

@login_required(login_url='login')
def profile(request):
    profile = Profile.objects.get(user=request.user.id)
    form = ProfileEdit(instance=request.user.profile)
    
    if request.method=='POST':
        form = ProfileEdit(request.POST,request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('profile')
    return render(request, 'all neighbours/profile.html',{"title":'Profile',"profile":profile,"form":form})

@login_required(login_url='login')
def business(request):
    user = request.user
    business = Business.objects.filter(neighborhood=user.profile.neighborhood).all()
    form = BusinessForm()
    if request.method=='POST':
        form = BusinessForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.cleaned_data['image']
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            neighborhood = form.cleaned_data['neighborhood']
            created = Business(image=image, name=name,email=email,neighborhood=neighborhood,user=request.user)
            created.save()
            
    return render(request, 'all neighbours/business.html',{"title":'Business/Events','form':form,"business":business,'user':user})

@login_required(login_url='login')
def contact(request):
    user = request.user
    if not user.profile:
        return render(request, 'all neighbours/nineOneone.html',{"title":'Emergency Contact','user':user})
    police = Contact.objects.get(name='police',neighborhood=user.profile.neighborhood)
    medics = Contact.objects.get(name='medics',neighborhood=user.profile.neighborhood)
    return render(request, 'all neighbours/nineOneone.html',{"title":'Emergency Contact','user':user,"police":police,"medics":medics})



def register(request):
    form = RegisterForm()
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('profile')
    return render(request, 'registration/register.html',{"title":'Register','form':form})
    

def post(request):
    form = PostForm()
    if request.method == 'POST':
        form =  PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    return render(request,'all neighbours/post.html',{'form':form})
# Create your views here.

neighbours/templates/all neighbours/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <link rel="icon" href='/static/Images/Hoodlum2.jpeg'>
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}"> {% if title %}
    <title>Majirani- {{ title }}</title>
    {% else %}
    <title>Majirani</title>
    {% endif %} {% block head %} {% endblock %}
</head>

<body>
    <header class="header">
        <nav class="header-nav">
            <article class="header-nav-list">
                <div class="header-nav-list-logo">
                    <a href="{% url 'home' %}">
                        <img src='/static/Images/Neighbourhood logo.jpg' alt="logo"> 
                    </a>
                </div>
                <div class="hamburger">
                    <span class="bar"></span>
                    <span class="bar"></span>
                    <span class="bar"></span>
                </div>
                <ul class="header-nav-list-ul">
                    <li><a href="{% url 'business' %}">Business</a></li>
                    <li><a href="{% url 'nineOneone' %}">Contact</a></li>
                    <li><a href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a href="{% url 'profile' %}">Profile</a></li>
                </ul>
            </article>
            <article class="header-nav-post">
                <button id="open">Post</button>
            </article>
            <article class="header-nav-menu">
                <ul>
                    <li><a href="{% url 'business' %}">Business</a></li>
                    <li><a href="{% url 'nineOneone' %}">Contact</a></li>
                    <li><a href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a href="{% url 'profile' %}">Profile</a></li>
                    <li><button id="open2">Post</button></li>
                </ul>
            </article>
        </nav>
    </header>
    {% block content %} {% endblock %}
</body>

</html>

neighbours/templates/all neighbours/business.html
{% extends 'all neighbours/base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/pop.css'%}">
<link rel="stylesheet" href="{% static 'css/business.css'%}">
<style>
    .none {
        display: none;
    }
</style>
{% endblock %} {% block content %}
<main class="main">
    <section class="main-post  none" id="post">
        <form action="" class="main-post-form" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            <div class="main-post-form-title">
                <h1>Event/Business</h1>
                <h2 id="close">&times;</h2>
            </div>
            <div class="main-post-form-input">
                {{form.image}}{{ form.name }} {{ form.email }} {{ form.neighborhood }}
            </div>
            <div class="main-post-form-submit">
                <button type="submit">Post</button>
            </div>
        </form>
    </section>
    <section class="main-landing">
        <h1>Business</h1>
    </section>
    <section class="main-business">
        {% if not user.profile.neighborhood %}
        <p class="not">You haven't Set a Neighboorhod in your Profile</p>
        {% else %} {% for bis in business %}
        <article class="main-business-one">
            <div class="main-business-one image">
                <img src="{{bis.image.url}}" alt="" class="image__img">
                <div class="image__overlay image__overlay--blur">
                    <p>{{ bis.name }}</p>
                </div>
            </div>
            <div class="main-business-one-title">
                <h1>{{ bis.name }}</h1>
            </div>
            <div class="main-business-one-email">
                <p><img src= '/static/Images/Email.png' alt="email"> {{bis.email}}</p>
            </div>
            <div class="main-business-one-owner">
                <p>By <span>{{ bis.user }}</span></p>
            </div>
        </article>
        {% endfor %} {%endif%}
    </section>
</main>
<script src="{% static 'js/nav.js'%}"></script>
<script src="{% static 'js/pop.js'%}"></script>
<script>
    $(document).ready(function() {
        $("#id_name").attr('placeholder', '{{form.name.label}}');
        $("#id_email").attr('placeholder', '{{form.email.label}}');
    });
</script>
{% endblock %}

neighbours/templates/all neighbours/index.html
{% extends 'all neighbours/base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/pop.css' %}">
<link rel="stylesheet" href="{% static 'css/footer.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<style>
    .none {
        display: none;
    }
</style>
{% endblock %} {% block content %}
<main class="main">
    <section class="main-post  none" id="post">
        <form action="" class="main-post-form" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            <div class="main-post-form-title">
                <h1>Event/Business</h1>
                <h2 id="close">&times;</h2>
            </div>
            <div class="main-post-form-input">
                {{ form.image }}{{ form.name }} {{ form.email }} {{ form.neighborhood }}
            </div>
            <div class="main-post-form-submit">
                <a href=" {% url 'post'%}"><button type="submit">Post</button></a>
                
                
            </div>
        </form>
    </section>
    <section class="main-landing">
        <article class="main-landing-title">
            <h1>GET INVOLVED WITH YOUR</h1>
            <h1>LOCAL COMMUNITY.</h1>
        </article>
        <article class="main-landing-search">
            <div class="main-landing-search-title">
                <h3>Enter name of business</h3>
            </div>
            <form class="main-landing-search-input" method="post">
                {% csrf_token %} {{ searchform.search }}
                <button type="submit"><img src='/static/Images/Neighbourhood logo.jpg' alt="search"></button>
            </form>
        </article>
    </section>
    <section class="main-description">
        <article class="main-description-bold">
            <h1>When Communities work together, safer neighborhoods become a reality.</h1>
        </article>
        <article class="main-description-light">
            <p>Today people don't know on doors to make friends.</p>
            <p>Technology has done alot so getting to know neigbours isn't that difficult nowdays.</p>
        </article>
    </section>
    <section class="main-extra">
        <article class="main-extra-prevention">
            <div class="main-extra-prevention-image">
                <img src='/static/Images/crime prevetion.png' alt=""> 
            </div>
            <div class="main-extra-prevention-title">
                <h2>Prevention</h2>
            </div>
            <div class="main-extra-prevention-desc">
                <p>Prevent crime by keeping you eyes and ears open and info your neighbours about security issues.</p>
            </div>
        </article>
        <article class="main-extra-focus">
            <div class="main-extra-focus-image">
                <img src='/static/Images/crime focus.jpeg'alt="">
            </div>
            <div class="main-extra-focus-title">
                <h2>Focus</h2>
            </div>
            <div class="main-extra-focus-desc">
                <p>
                    Communication is focused on local safety and security no chit chat.Alerts are guided and structured preventing them from becoming off topic.</p>
            </div>
        </article>
        <article class="main-extra-informed">
            <div class="main-extra-informed-image">
                <img src='/static/Images/crime awarenes.jpg' alt="">
            </div>
            <div class="main-extra-informed-title">
                <h2>Stay Informed</h2>
            </div>
            <div class="main-extra-informed-desc">
                <p>Prevent crime by keeping your eyes and ears open and info your neighbours about security issues.</p>
            </div>
        </article>
    </section>
    <section class="footer">
        <article class="footer-content">
            <p>Crafted with</p>
            <p>By <span>Kelvin Wepo</span></p>
        </article>
    </section>
</main>
<script src="{% static 'js/nav.js' %}"></script>
<script src="{% static 'js/pop.js' %}"></script>
<script>
    $(document).ready(function() {
        $("#id_name").attr('placeholder', 'Business/Event');
        $("#id_email").attr('placeholder', '{{form.email.label}}');
        $("#id_search").attr('placeholder', 'Search');
    });
</script>
{% endblock %}

neighbours/templates/all neighbours/nineOneone.html
{% extends 'all neighbours/base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/nineOneone.css'%}"> {% endblock %} {% block content %}
<main class="main">
    <section class="main-landing">
        <h1>Emergency Contacts</h1>
    </section>
    <section class="main-contacts">
        {% if not user.profile.neighborhood %}
        <p class="not">You haven't Set a Neighboorhod in your Profile</p>
        {% else %}
        <article class="main-contacts-medical">
            <div class="main-contacts-medical-image">
                <img src='/static/Images/ambulance.jpeg' alt="ambulance">
            </div>
            <h1>Local Medical Number</h1>
            <p>{{medics.number}}</p>
        </article>
        <article class="main-contacts-global">
            <div class="main-contacts-global-image">
                <img src='/static/Images/siren.jpeg' alt="global">
            </div>
            <h1>Global emergency Number</h1>
            <p>911</p>
        </article>
        <article class="main-contacts-police">
            <div class="main-contacts-police-image">
                <img src='/static/Images/police car.png' alt="police">
            </div>
            <h1>Local Police Number</h1>
            <p>{{ police.number }}</p>
        </article>
        {% endif %}
    </section>
</main>
<script src="{% static 'js/nav.js' %}"></script>
{% endblock %}

neighbours/templates/all neighbours/post.html
<form action="" method="post" enctype="multipart/form-data" class="w-50 ">
    {%csrf_token%}
    {% bootstrap_form form%}
    <input type="submit" class="btn btn-outline-info " value="Post">
</form>

neighbours/templates/all neighbours/profile.html
{% extends 'all neighbours/base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}"> {% endblock %} {% block content %}
<main class="main">
    <section class="main-profile">
        <article class="main-profile-title">
            <div class="main-profile-title-image">
                {% if not profile.image.url %}
                <img src='/static/Images/default avatar.png' alt=""> {% else %}
                <img src="{{profile.image.url}}" alt=""> {% endif %}
            </div>
            <div class="main-profile-title-desc">
                <h1>{{ profile.username }}</h1>
                <p>{{ profile.email }}</p>
            </div>
        </article>
        <article class="main-profile-bio">
            <div class="main-profile-bio-title">
                <h1>BIO</h1>
            </div>
            <div class="main-profile-bio-bio">
                {% if not profile.bio %}
                <p>Tell us about yourself</p> {% else %}
                <p>{{ profile.bio }}</p> {% endif %}
            </div>
        </article>
        <article class="main-profile-form">
            <form action="" class="main-profile-form-form" method="post" enctype='multipart/form-data'>
                {% csrf_token %}
                <div class="main-profile-form-form-name">
                    {{ form.image }}
                </div>
                <div class="main-profile-form-form-name">
                    {{ form.username }}
                </div>
                <div class="main-profile-form-form-email">
                    {{ form.email }}
                </div>
                <div class="main-profile-form-form-location">
                    {{ form.neighborhood }}
                </div>
                <div class="main-profile-form-form-bio">
                    {{ form.bio }}
                </div>
                <div class="main-profile-form-form-submit">
                    <button type="submit">Update</button>
                </div>
            </form>
        </article>
    </section>
</main>
<script src="{% static 'js/nav.js' %}"></script>
<script>
    $(document).ready(function() {
        $("#id_neighborhood").attr('placeholder', '{{form.neighborhood.label}}');
    });
</script>
{% endblock %}